spring.application.name=eventplatform

spring.datasource.url=jdbc:mysql://localhost:3306/eventplatform
spring.datasource.username=root
spring.datasource.password=

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

jwt.secret=eventplatform_secret_key_2025_very_long_and_secure
jwt.expiration=86400000

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

logging.level.com.universite.eventplatform=DEBUG
server.port=8080